# Generated by Django 4.2.5 on 2024-11-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prix', models.FloatField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('tag', models.ManyToManyField(blank=True, to='produit.tag')),
            ],
        ),
    ]
