# Generated by Django 4.2.5 on 2024-11-06 00:39

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('package_choice', models.CharField(choices=[('PDOS', 'Pack Dossier'), ('PVST', 'Pack Visite'), ('PBAS', 'Pack Basique'), ('PBST', 'Pack Booster'), ('PPRE', 'Pack Premium'), ('PCNC', 'Pack Conciergerie')], default='PDOS', max_length=4, verbose_name='Confirmer votre pack')),
                ('personne_foyer', models.IntegerField(blank=True, null=True, verbose_name='Nombre de personnes dans le foyer')),
                ('situation_matrimo', models.CharField(choices=[('MARR', 'Marrié (e)'), ('DIVO', 'Divorcé (e)'), ('CELI', 'Célibataire'), ('SEPA', 'Séparé (e)'), ('VEUF', 'Veuf (ve)')], default='CELI', max_length=4, verbose_name='Situation matrimoniale')),
                ('referent', models.CharField(blank=True, max_length=100, null=True)),
                ('lieuRecherche', models.CharField(blank=True, max_length=100, null=True)),
                ('typeBien', models.CharField(blank=True, max_length=100, null=True)),
                ('budgetLoyer', models.IntegerField(null=True)),
                ('SalaireFoyer', models.IntegerField(null=True)),
                ('motifDemenag', models.TextField(blank=True, max_length=3000, null=True)),
                ('precisRecherche', models.TextField(blank=True, max_length=3000, null=True)),
                ('document_avis', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail")),
                ('document_paye', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 2: 3 dernières fiches de payes, pièces d'identité")),
                ('document_quittance', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Pièce 3: 3 dernières quittance de loyers')),
                ('address1', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='Adresse')),
                ('address2', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address', verbose_name='')),
                ('city', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='address.address', verbose_name='Ville')),
                ('country', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='address.address', verbose_name='Pays')),
                ('postalCode', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities_country', to='address.address', verbose_name='Code Postal')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
