# Generated by Django 4.2.1 on 2025-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'verbose_name': 'Client'},
        ),
        migrations.AddField(
            model_name='client',
            name='type_utilisateur',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('proprietaire', 'Propriétaire'), ('partenaire', 'Partenaire')], default='locataire', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
