# Generated by Django 4.2.1 on 2025-06-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonce', '0002_equipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='locataire_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_interessees', to=settings.AUTH_USER_MODEL, verbose_name='Locataire intéressé'),
        ),
    ]
