# Generated by Django 4.2.1 on 2025-06-21 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonce', '0003_annonce_locataire_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPaiementCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_caution_total', models.FloatField(verbose_name='Montant total de la caution')),
                ('nombre_mensualites', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Nombre de mensualités')),
                ('montant_mensuel', models.FloatField(verbose_name='Montant mensuel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=10, verbose_name='Statut du plan')),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_paiement_caution', to='annonce.annonce')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_paiement_caution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementMensuelCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mensualite', models.IntegerField(verbose_name='Numéro de la mensualité')),
                ('montant', models.FloatField(verbose_name='Montant de la mensualité')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=10, verbose_name='Statut du paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_mensuels', to='annonce.planpaiementcaution')),
            ],
            options={
                'ordering': ['numero_mensualite'],
                'unique_together': {('plan_paiement', 'numero_mensualite')},
            },
        ),
    ]
