# Generated by Django 4.2.1 on 2025-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcli',
            name='cli_type_bien',
            field=models.CharField(choices=[('studio', 'Studio'), ('t1', 'T1 (1 pièce)'), ('t2', 'T2 (2 pièces)'), ('t3', 'T3 (3 pièces)'), ('t4', 'T4 (4 pièces)'), ('t5', 'T5 (5 pièces)'), ('t6_plus', 'T6 et plus'), ('maison_2_pieces', 'Maison 2 pièces'), ('maison_3_pieces', 'Maison 3 pièces'), ('maison_4_pieces', 'Maison 4 pièces'), ('maison_5_pieces', 'Maison 5 pièces'), ('maison_6_pieces_plus', 'Maison 6 pièces et plus'), ('loft', 'Loft'), ('duplex', 'Duplex')], help_text='Maison ou Appart et taille', max_length=100, verbose_name='Type de bien'),
        ),
    ]
