# Generated by Django 4.2.1 on 2025-06-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0002_alter_clientcli_cli_type_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcli',
            name='cli_lieu_recherche',
            field=models.CharField(choices=[('paris', 'Paris'), ('lyon', 'Lyon'), ('marseille', 'Marseille'), ('toulouse', 'Toulouse'), ('nice', 'Nice'), ('nantes', 'Nantes'), ('montpellier', 'Montpellier'), ('strasbourg', 'Strasbourg'), ('bordeaux', 'Bordeaux'), ('lille', 'Lille'), ('rennes', 'Rennes'), ('reims', 'Reims'), ('le_havre', 'Le Havre'), ('saint_etienne', 'Saint-Étienne'), ('toulon', 'Toulon'), ('grenoble', 'Grenoble'), ('dijon', 'Dijon'), ('angers', 'Angers'), ('nimes', 'Nîmes'), ('villeurbanne', 'Villeurbanne'), ('clermont_ferrand', 'Clermont-Ferrand'), ('aix_en_provence', 'Aix-en-Provence'), ('brest', 'Brest'), ('limoges', 'Limoges'), ('tours', 'Tours'), ('amiens', 'Amiens'), ('perpignan', 'Perpignan'), ('metz', 'Metz'), ('besancon', 'Besançon'), ('orleans', 'Orléans'), ('rouen', 'Rouen'), ('mulhouse', 'Mulhouse'), ('caen', 'Caen'), ('nancy', 'Nancy'), ('argenteuil', 'Argenteuil'), ('montreuil', 'Montreuil'), ('roubaix', 'Roubaix'), ('tourcoing', 'Tourcoing'), ('avignon', 'Avignon'), ('dunkerque', 'Dunkerque'), ('banlieue_parisienne', 'Banlieue parisienne'), ('ile_de_france', 'Île-de-France (hors Paris)'), ('autres', 'Autres villes')], max_length=100, null=True, verbose_name='Lieu de recherche'),
        ),
    ]
