# Generated by Django 4.2.1 on 2025-06-13 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0003_alter_clientcli_cli_lieu_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcli',
            name='cli_contact',
            field=models.CharField(help_text='Format: +33123456789 ou 0123456789', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format français: +33123456789 ou 0123456789', regex='^(\\+33|0)[1-9](\\d{8})$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='clientcli',
            name='cli_email',
            field=models.EmailField(help_text='Format: exemple@domaine.com', max_length=100, null=True, verbose_name='Adresse email'),
        ),
    ]
