# Generated by Django 4.2.1 on 2025-06-13 00:52

import django.core.validators
from django.db import migrations, models
import soumission.models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0004_alter_clientcli_cli_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcli',
            name='cli_contact',
            field=models.CharField(help_text='Format: +33123456789 ou 0123456789 (uniquement des chiffres)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format français valide: +33123456789 ou 0123456789 (uniquement des chiffres)', regex='^(\\+33[1-9]\\d{8}|0[1-9]\\d{8})$'), soumission.models.validate_phone_number], verbose_name='Numéro de téléphone'),
        ),
    ]
