# Generated by Django 4.2.5 on 2024-11-06 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(blank=True, max_length=20)),
                ('voie', models.CharField(blank=True, max_length=35)),
                ('ville', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('pays', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire_demeya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire_nek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('type_visite', models.CharField(choices=[('0', 'Visites substituées'), ('1', 'Visites physiques')], max_length=30, null=True)),
                ('heure_debut', models.TimeField(null=True)),
                ('heure_fin', models.TimeField(null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_reunion', models.DateTimeField(null=True)),
                ('package_choice', models.CharField(choices=[('PDOS', 'Pack Dossier'), ('PVST', 'Pack Visite'), ('PBAS', 'Pack Basique'), ('PBST', 'Pack Booster'), ('PPRE', 'Pack Premium'), ('PCNC', 'Pack Conciergerie')], default='PDOS', max_length=4, verbose_name='Confirmer votre pack')),
                ('personne_foyer', models.IntegerField(blank=True, null=True, verbose_name='Nombre de personnes dans le foyer')),
                ('situation_matrimo', models.CharField(choices=[('MARR', 'Marrié (e)'), ('DIVO', 'Divorcé (e)'), ('CELI', 'Célibataire'), ('SEPA', 'Séparé (e)'), ('VEUF', 'Veuf (ve)')], default='CELI', max_length=4, verbose_name='Situation matrimoniale')),
                ('referent', models.CharField(blank=True, max_length=100, null=True)),
                ('lieuRecherche', models.CharField(blank=True, max_length=100, null=True)),
                ('typeBien', models.CharField(blank=True, max_length=100, null=True)),
                ('budgetLoyer', models.IntegerField(null=True)),
                ('SalaireFoyer', models.IntegerField(null=True)),
                ('motifDemenag', models.TextField(blank=True, max_length=3000, null=True)),
                ('precisRecherche', models.TextField(blank=True, max_length=3000, null=True)),
                ('document_avis', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail")),
                ('document_paye', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 2: 3 dernières fiches de payes, pièces d'identité")),
                ('document_quittance', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Pièce 3: 3 dernières quittance de loyers')),
                ('verdict', models.CharField(choices=[('acct', 'Accepté'), ('attn', 'Attente'), ('refu', 'Refusé')], default='refu', max_length=4, verbose_name='Verdict')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.adressworkflow')),
                ('bilan_semaine', models.ManyToManyField(null=True, to='workflow.bilan')),
                ('commentaire_demaya', models.ManyToManyField(null=True, to='workflow.commentaire_demeya')),
                ('commentaire_nek', models.ManyToManyField(null=True, to='workflow.commentaire_nek')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
